### ISSUE TITLE
 Negative indexing is not supported.

### ISSUE THREAD

**Issue by nirajpoudel** [coderaman07/Django-ECommerce-Website#1]
while I am running the project it says

`AssertionError at /
Negative indexing is not supported.
`
![Screenshot from 2021-09-14 20-39-47](https://user-images.githubusercontent.com/59787504/133281717-98b40062-d8b3-4294-909f-45a7ecf9edb6.png)

**Comment by coderaman07** [comment]
Have you added any Product in your Database through /admin ??

The Project is designed in way where the Latest Product will be fetched from the Database and will be prioritized at it's the Latest and at sale.

**Comment by nirajpoudel** [comment]
After adding product it worked!!

Thank you.
